name: flutter_dio_plus
description: "A flutter package to API handling like a super boss 😎."
version: 0.0.10
homepage: https://github.com/AbdOoSaed/flutter_dio_plus

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ">=4.0.0 <5.0.0"
  connectivity_plus: ">=1.0.0 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ">=1.0.0 <2.0.0"
  mockito: ">=5.0.0 <6.0.0"
  build_runner: ">=2.0.0 <3.0.0"
  flutter_lints: ">=1.0.0 <2.0.0"

flutter:
