name: api_manger
description: "A flutter package to API handling like a super boss 😎."
version: 0.0.3
homepage: https://github.com/AbdOoSaed/api_manger

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ">=4.0.0 <5.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
